#!/usr/bin/env bash
# shellcheck shell=bash
# Loaded by scripts/install.sh. Resolve this file with BASH_SOURCE so
# callers may source install.sh from any current working directory.
#
# Claude API secrets are deliberately dual-path:
# - ~/.agent-runtime/secrets/claude/<provider>.env is the launcher-visible
#   shared provider file.
# - ~/.agents/secrets/claude/<provider>/<seat>.env is the agent-admin
#   seat-specific file written into session.toml.
# Template-driven seeding should preserve real tokens in both locations when the
# incoming template or installer-provided token is only a placeholder.
_CLAWSEAT_INSTALL_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

seat_secret_file_for() {
  local seat="$1" seat_auth_mode seat_provider
  seat_auth_mode="$(seat_auth_mode_for_provider_mode)"
  seat_provider="$(seat_provider_for_provider_mode)"
  case "$seat_auth_mode" in
    api) printf '%s\n' "$HOME/.agents/secrets/claude/$seat_provider/$seat.env" ;;
    oauth|oauth_token) return 0 ;;
    *) die 22 PROVIDER_MODE_UNKNOWN "unsupported seat auth mode for secret seeding: $seat_auth_mode" ;;
  esac
}

seat_secret_file_for_provider() {
  local seat="$1" provider="$2"
  local index=0 path=""
  while IFS= read -r path; do
    if [[ "$index" -eq 1 ]]; then
      printf '%s\n' "$path"
      return 0
    fi
    index=$((index + 1))
  done < <(_claude_secret_paths "$provider" "$seat")
}

global_claude_secret_template_for_provider() {
  local provider="$1"
  local path=""
  while IFS= read -r path; do
    printf '%s\n' "$path"
    return 0
  done < <(_claude_secret_paths "$provider")
}

_claude_secret_paths() {
  local provider="$1" seat="${2:-}"
  printf '%s\n' "$HOME/.agent-runtime/secrets/claude/$provider.env"
  if [[ -n "$seat" ]]; then
    printf '%s\n' "$HOME/.agents/secrets/claude/$provider/$seat.env"
  fi
}

write_bootstrap_secret_file() {
  local path="$1"
  mkdir -p "$(dirname "$path")" || die 31 PROJECT_SECRET_DIR_FAILED "unable to create $(dirname "$path")"
  {
    printf '# generated by scripts/install.sh for project=%s\n' "$PROJECT"
    case "$PROVIDER_MODE" in
      minimax)
        export_line ANTHROPIC_AUTH_TOKEN "$PROVIDER_KEY"
        export_line ANTHROPIC_BASE_URL "$(provider_base_or_default minimax "$PROVIDER_BASE")"
        export_line ANTHROPIC_MODEL "${PROVIDER_MODEL:-MiniMax-M2.7-highspeed}"
        ;;
      deepseek)
        export_line ANTHROPIC_AUTH_TOKEN "$PROVIDER_KEY"
        export_line ANTHROPIC_BASE_URL "$(provider_base_or_default deepseek "$PROVIDER_BASE")"
        export_line ANTHROPIC_MODEL "${PROVIDER_MODEL:-deepseek-v4-pro[1M]}"
        ;;
      ark)
        export_line ANTHROPIC_AUTH_TOKEN "$PROVIDER_KEY"
        export_line ANTHROPIC_BASE_URL "$(provider_base_or_default ark "$PROVIDER_BASE")"
        export_line ANTHROPIC_MODEL "${PROVIDER_MODEL:-ark-code-latest}"
        ;;
      xcode-best)
        export_line ANTHROPIC_AUTH_TOKEN "$PROVIDER_KEY"
        export_line ANTHROPIC_BASE_URL "$(provider_base_or_default xcode-best "$PROVIDER_BASE")"
        if [[ -n "$PROVIDER_MODEL" ]]; then
          export_line ANTHROPIC_MODEL "$PROVIDER_MODEL"
        fi
        ;;
      custom_api)
        export_line ANTHROPIC_API_KEY "$PROVIDER_KEY"
        export_line ANTHROPIC_AUTH_TOKEN "$PROVIDER_KEY"
        export_line ANTHROPIC_BASE_URL "${PROVIDER_BASE:-$(provider_base_or_default anthropic_console)}"
        if [[ -n "$PROVIDER_MODEL" ]]; then
          export_line ANTHROPIC_MODEL "$PROVIDER_MODEL"
        fi
        ;;
      anthropic_console)
        export_line ANTHROPIC_API_KEY "$PROVIDER_KEY"
        if [[ -n "$PROVIDER_BASE" ]]; then
          export_line ANTHROPIC_BASE_URL "$PROVIDER_BASE"
        fi
        if [[ -n "$PROVIDER_MODEL" ]]; then
          export_line ANTHROPIC_MODEL "$PROVIDER_MODEL"
        fi
        ;;
      oauth_token)
        export_line CLAUDE_CODE_OAUTH_TOKEN "$PROVIDER_KEY"
        ;;
      oauth)
        ;;
      *)
        die 22 PROVIDER_MODE_UNKNOWN "unknown provider mode for secret seeding: $PROVIDER_MODE"
        ;;
    esac
  } >"$path" || die 31 PROJECT_SECRET_WRITE_FAILED "unable to write $path"
  chmod 600 "$path" || die 31 PROJECT_SECRET_CHMOD_FAILED "unable to chmod $path"
}

_secret_file_auth_token() {
  local path="$1"
  [[ -f "$path" ]] || return 1
  local token
  token="$(
    grep -m1 -E '^(export )?(ANTHROPIC_AUTH_TOKEN|ANTHROPIC_API_KEY|CLAUDE_CODE_OAUTH_TOKEN)=' "$path" \
      | sed -E 's/^(export )?(ANTHROPIC_AUTH_TOKEN|ANTHROPIC_API_KEY|CLAUDE_CODE_OAUTH_TOKEN)=//'
  )" || return 1
  [[ -n "$token" ]] || return 1
  printf '%s\n' "$token"
}

_secret_value_is_placeholder_token() {
  local value="${1:-}"
  local normalized
  [[ -n "$value" ]] || return 1
  normalized="$(printf '%s\n' "$value" | tr '[:upper:]' '[:lower:]')"
  case "$normalized" in
    '<set-by-operator>'|\
    'your_token_here'|\
    '<MINIMAX_TOKEN>'|\
    'deepseek-token'|\
    'dry-run-placeholder'|\
    'dry-run-placeholder-key'|\
    'dry-run-placeholder-token'|\
    'placeholder'|\
    'dummy'|\
    'example')
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

_secret_file_has_real_token() {
  local path="$1"
  local token
  token="$(_secret_file_auth_token "$path")" || return 1
  [[ -n "$token" ]] || return 1
  ! _secret_value_is_placeholder_token "$token"
}

_secret_file_has_placeholder_token() {
  local path="$1"
  local token
  token="$(_secret_file_auth_token "$path")" || return 1
  _secret_value_is_placeholder_token "$token"
}

_write_runtime_secret_env() {
  local provider="$1" runtime_path="$2"
  [[ "$provider" == "$PROVIDER_MODE" ]] || return 1
  [[ -n "$PROVIDER_KEY" ]] || return 1
  if _secret_file_has_real_token "$runtime_path" && _secret_value_is_placeholder_token "$PROVIDER_KEY"; then
    warn "runtime secret preserved for provider $provider; placeholder input would overwrite real token: $runtime_path"
    chmod 600 "$runtime_path" || die 31 PROJECT_SECRET_CHMOD_FAILED "unable to chmod $runtime_path"
    return 0
  fi
  write_bootstrap_secret_file "$runtime_path"
}

_copy_secret_template_preserving_real_token() {
  local src_path="$1" secret_path="$2" seat="$3"
  if _secret_file_has_real_token "$secret_path" && _secret_file_has_placeholder_token "$src_path"; then
    warn "seat secret preserved for $seat; placeholder template would overwrite real token: $secret_path"
    chmod 600 "$secret_path" || die 31 PROJECT_SECRET_CHMOD_FAILED "unable to chmod $secret_path"
    return 0
  fi
  cp "$src_path" "$secret_path" || die 31 PROJECT_SECRET_WRITE_FAILED "unable to copy $src_path -> $secret_path"
  chmod 600 "$secret_path" || die 31 PROJECT_SECRET_CHMOD_FAILED "unable to chmod $secret_path"
}

seed_bootstrap_secrets() {
  note "Step 5.6: seed template-driven seat secrets"
  local seat secret_path src_path provider auth tool model path_index path
  if [[ "$DRY_RUN" == "1" ]]; then
    for seat in "${PENDING_SEATS[@]}"; do
      # Dry-run must stay non-fatal even when the legacy template file is
      # absent (for example clawseat-creative after the BV-2 cleanup). In that
      # case we skip the per-seat copy trace instead of tripping `read` on EOF.
      local template_line=""
      template_line="$(template_seat_config "$seat" 2>/dev/null || true)"
      [[ -n "$template_line" ]] || continue
      read -r tool auth provider model <<<"$template_line"
      if [[ -n "$FORCE_ALL_API_PROVIDER" && "$auth" == "api" ]]; then
        provider="$(seat_provider_for_explicit_provider "$FORCE_ALL_API_PROVIDER")"
      fi
      [[ "$auth" == "api" && "$tool" == "claude" ]] || continue
      path_index=0
      src_path=""
      secret_path=""
      while IFS= read -r path; do
        if [[ "$path_index" -eq 0 ]]; then
          src_path="$path"
        else
          secret_path="$path"
        fi
        path_index=$((path_index + 1))
      done < <(_claude_secret_paths "$provider" "$seat")
      printf '[dry-run] copy %s -> %s\n' "$src_path" "$secret_path"
    done
    return 0
  fi

  local seed_source="$PROJECT_RECORD_PATH"
  [[ -f "$seed_source" ]] || seed_source="$PROJECT_LOCAL_TOML"
  "$PYTHON_BIN" - "$seed_source" "${PENDING_SEATS[@]}" <<'PY' |
from __future__ import annotations

import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore

path = Path(sys.argv[1])
pending = set(sys.argv[2:])
if not path.exists():
    raise SystemExit(0)
data = tomllib.loads(path.read_text(encoding="utf-8"))
if isinstance(data.get("overrides"), list):
    overrides = {
        str(item.get("id", "")): item
        for item in data.get("overrides", [])
        if str(item.get("id", ""))
    }
    seats = [seat for seat in sys.argv[2:] if seat in overrides]
else:
    overrides = data.get("seat_overrides") or {}
    seats = [str(seat) for seat in data.get("engineers", [])]
for seat in seats:
    if seat not in pending:
        continue
    override = overrides.get(seat) or {}
    tool = str(override.get("tool", "claude"))
    auth = str(override.get("auth_mode", "oauth"))
    provider = str(override.get("provider", "anthropic"))
    model = str(override.get("model", ""))
    print("\t".join((seat, tool, auth, provider, model)))
PY
  while IFS=$'\t' read -r seat tool auth provider model; do
    [[ -n "$seat" ]] || continue
    [[ "$tool" == "claude" && "$auth" == "api" ]] || continue
    path_index=0
    src_path=""
    secret_path=""
    while IFS= read -r path; do
      if [[ "$path_index" -eq 0 ]]; then
        src_path="$path"
      else
        secret_path="$path"
      fi
      path_index=$((path_index + 1))
    done < <(_claude_secret_paths "$provider" "$seat")
    _write_runtime_secret_env "$provider" "$src_path" || true
    if [[ ! -f "$src_path" ]]; then
      warn "seat secret skipped for $seat; missing shared template: $src_path"
      continue
    fi
    mkdir -p "$(dirname "$secret_path")" || die 31 PROJECT_SECRET_DIR_FAILED "unable to create $(dirname "$secret_path")"
    _copy_secret_template_preserving_real_token "$src_path" "$secret_path" "$seat"
  done
}

ensure_privacy_kb_template() {
  note "Step 5.7: ensure machine privacy KB"
  local privacy_path="$HOME/.agents/memory/machine/privacy.md"
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '[dry-run] ensure %s exists with mode 0600\n' "$privacy_path"
    return 0
  fi
  if [[ -e "$privacy_path" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$privacy_path")" || die 31 PRIVACY_KB_DIR_FAILED "unable to create $(dirname "$privacy_path")"
  (umask 077; cat >"$privacy_path" <<'EOF'
# Privacy KB
# Operator manually maintains. Lines starting with BLOCK: are forbidden patterns.
# Example: BLOCK: sk-
# Example: BLOCK: ghp_
EOF
  ) || die 31 PRIVACY_KB_WRITE_FAILED "unable to write $privacy_path"
  chmod 600 "$privacy_path" || die 31 PRIVACY_KB_CHMOD_FAILED "unable to chmod $privacy_path"
}

ensure_deepseek_secret_template() {
  note "Step 5.8: ensure DeepSeek shared secret template"
  local secret_path="$HOME/.agent-runtime/secrets/claude/deepseek.env"
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '[dry-run] ensure %s exists with mode 0600\n' "$secret_path"
    return 0
  fi
  if [[ -e "$secret_path" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$secret_path")" || die 31 DEEPSEEK_SECRET_DIR_FAILED "unable to create $(dirname "$secret_path")"
  (umask 077; cat >"$secret_path" <<'EOF'
ANTHROPIC_AUTH_TOKEN=<set-by-operator>
ANTHROPIC_BASE_URL=https://api.deepseek.com/anthropic
ANTHROPIC_MODEL=deepseek-v4-pro[1M]
EOF
  ) || die 31 DEEPSEEK_SECRET_WRITE_FAILED "unable to write $secret_path"
  chmod 600 "$secret_path" || die 31 DEEPSEEK_SECRET_CHMOD_FAILED "unable to chmod $secret_path"
}
