from __future__ import annotations

import sys
from pathlib import Path
from types import SimpleNamespace


_REPO = Path(__file__).resolve().parents[1]
_SCRIPTS = _REPO / "core" / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from agent_admin_template import TemplateHandlers, TemplateHooks  # noqa: E402


def _handlers(engineer: SimpleNamespace) -> TemplateHandlers:
    def write_text(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    hooks = TemplateHooks(
        ensure_dir=lambda path: path.mkdir(parents=True, exist_ok=True),
        write_text=write_text,
        load_engineer=lambda _seat: engineer,
        project_template_context=lambda _project: None,
        q=lambda value: value,
        render_authority_lines=lambda _engineer: [],
        render_protocol_reminder_lines=lambda _engineer, _role, **_: [],
        render_read_first_lines=lambda _session, _project, _engineer: [],
        render_harness_runtime_lines=lambda _engineer: [],
        render_project_seat_map_lines=lambda *args, **kwargs: [],
        render_seat_boundary_lines=lambda _session, _engineer: [],
        render_communication_protocol_lines=lambda _engineer, _project, **_: [],
        render_dispatch_playbook_lines=lambda _session, _project, _engineer: [],
        render_loaded_skills_lines=lambda _engineer, _seat: [],
        render_optional_skills_catalog=lambda _skills: "",
        workspace_contract_payload=lambda *args, **kwargs: {"project": "install"},
        workspace_contract_fingerprint=lambda _payload: "fp-test",
        render_workspace_contract_text=lambda *args, **kwargs: "contract = true\n",
        render_role_line=lambda _engineer, _compact: "",
        render_role_details_lines=lambda _engineer: [],
        render_aliases_lines=lambda _engineer: [],
        render_heartbeat_text=lambda _session, _project, _engineer: None,
        render_heartbeat_manifest_text=lambda *args, **kwargs: None,
    )
    return TemplateHandlers(hooks)


def _engineer() -> SimpleNamespace:
    return SimpleNamespace(
        engineer_id="planner",
        role="planner-dispatcher",
        role_details=[],
        aliases=[],
        skills=[],
    )


def _project(tmp_path: Path) -> SimpleNamespace:
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    return SimpleNamespace(name="install", repo_root=str(repo_root), tasks_root=str(tmp_path / "tasks"))


def _session(tool: str, workspace: Path) -> SimpleNamespace:
    return SimpleNamespace(
        engineer_id="planner",
        project="install",
        tool=tool,
        workspace=str(workspace),
        auth_mode="oauth",
        provider="",
    )


def test_gemini_workspace_render_writes_geminiignore(tmp_path) -> None:
    workspace = tmp_path / "gemini-workspace"
    _handlers(_engineer()).apply_template(_session("gemini", workspace), _project(tmp_path))

    ignore = workspace / ".geminiignore"
    text = ignore.read_text(encoding="utf-8")
    assert "generated by clawseat workspace render" in text
    assert "core/skills/" in text
    assert "repos/" in text
    assert ".tasks/*/handoffs/" in text
    assert "*.bak.*" in text
    assert "*.consumed" in text


def test_non_gemini_workspace_render_does_not_write_geminiignore(tmp_path) -> None:
    workspace = tmp_path / "claude-workspace"
    workspace.mkdir()
    stale = workspace / ".geminiignore"
    stale.write_text("# generated by clawseat workspace render\nold generated file\n", encoding="utf-8")

    _handlers(_engineer()).apply_template(_session("claude", workspace), _project(tmp_path))

    assert not stale.exists()
