"""BM: _secret_file_has_real_token preserves non-sk- tokens."""
from __future__ import annotations

import subprocess
from pathlib import Path

SECRETS_SH = Path(__file__).resolve().parents[1] / "scripts" / "install" / "lib" / "secrets.sh"


def _run_guard(tmp_path: Path, content: str) -> bool:
    """Returns True if _secret_file_has_real_token says file has real token."""
    env_file = tmp_path / "test.env"
    env_file.write_text(content, encoding="utf-8")
    result = subprocess.run(
        ["bash", "-c",
         f"source {SECRETS_SH} && _secret_file_has_real_token {env_file} && echo REAL || echo PLACEHOLDER"],
        capture_output=True, text=True, check=False,
    )
    return "REAL" in result.stdout


def test_non_sk_minimax_runtime_token_preserved(tmp_path: Path) -> None:
    """Non-sk- minimax token (e.g. minimax-secret-xxx) is treated as real."""
    content = "ANTHROPIC_AUTH_TOKEN=<ANTHROPIC_AUTH_TOKEN>" + "x" * 24 + "\n"
    assert _run_guard(tmp_path, content), "non-sk- real token should be preserved"


def test_placeholder_minimax_token_not_preserved(tmp_path: Path) -> None:
    """Known placeholder <MINIMAX_TOKEN> is not treated as real."""
    content = "ANTHROPIC_AUTH_TOKEN=<ANTHROPIC_AUTH_TOKEN>\n"
    assert not _run_guard(tmp_path, content), "placeholder should NOT be preserved"


def test_sk_prefix_token_still_preserved(tmp_path: Path) -> None:
    """sk- tokens still treated as real (backward compat)."""
    content = "ANTHROPIC_AUTH_TOKEN=<ANTHROPIC_AUTH_TOKEN>-" + "a" * 30 + "\n"
    assert _run_guard(tmp_path, content), "sk- token should be preserved"


def test_export_prefixed_file_real_token(tmp_path: Path) -> None:
    """File with 'export ANTHROPIC_AUTH_TOKEN=...' format is parsed correctly."""
    content = (
        "# generated by install.sh\n"
        "export ANTHROPIC_AUTH_TOKEN=<ANTHROPIC_AUTH_TOKEN>" + "y" * 24 + "\n"
        "export ANTHROPIC_BASE_URL=https://api.minimaxi.com/anthropic\n"
    )
    assert _run_guard(tmp_path, content), "export-prefixed real token should be preserved"


def test_export_prefixed_placeholder_not_preserved(tmp_path: Path) -> None:
    """export ANTHROPIC_AUTH_TOKEN=<ANTHROPIC_AUTH_TOKEN> is a placeholder."""
    content = (
        "# generated by install.sh\n"
        "export ANTHROPIC_AUTH_TOKEN=<ANTHROPIC_AUTH_TOKEN>\n"
        "export ANTHROPIC_BASE_URL=https://api.minimaxi.com/anthropic\n"
    )
    assert not _run_guard(tmp_path, content), "export-prefixed placeholder should NOT be preserved"
