"""Phase 4 STS dogfood — honest-scoped integration tests.

These tests do NOT exercise a real planner seat end-to-end. They cover three
discrete real-CLI integration slices, named for what they actually validate:

1. install.sh --mode multi → render compatible with runtime profile loader
2. agent_admin brief queue / list / claim via canonical CLI entrypoint
3. Contract publish + drift cycle through CLI
4. Fuzz harness on a real EffectExpression DSL primitive set

A *true* E2E covering live planner pull, builder dispatch, acceptance_executor
invocation by planner, and chain-end relay requires running tmux seats and
is outside Phase 4 scope. The reviewer audit (round 6) flagged the prior
test name "test_sts_dogfood_full_chain" as misleading because it bypassed the
planner — this file restores honest naming.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "core" / "lib"))
sys.path.insert(0, str(REPO_ROOT / "core" / "scripts"))
sys.path.insert(0, str(REPO_ROOT / "core" / "skills" / "planner" / "scripts"))


@pytest.fixture
def env_home(tmp_path, monkeypatch):
    monkeypatch.setenv("CLAWSEAT_REAL_HOME", str(tmp_path))
    monkeypatch.delenv("HOME", raising=False)
    return tmp_path


def _make_approved_config(proposals_dir: Path, team: str, project: str,
                           seats: list[dict]) -> None:
    proposals_dir.mkdir(parents=True, exist_ok=True)
    data = {
        "project": project,
        "team": team,
        "proposal_status": "approved",
        "operator_approved_ts": "2026-05-14T00:00:00+00:00",
        "seats": seats,
        "estimated_monthly_cost_usd": {"low": 50, "high": 100},
    }
    (proposals_dir / f"{team}__approved.yaml").write_text(
        "---\n" + yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
        + "---\n",
        encoding="utf-8",
    )


def _run_canonical_install_multi(env_home: Path, project: str, teams: list[str]) -> str:
    """Invoke install.sh --mode multi (the canonical entry point, not
    install_multi.sh directly). Returns stdout."""
    script = REPO_ROOT / "scripts" / "install.sh"
    proc = subprocess.run(
        ["bash", str(script),
         "--project", project,
         "--mode", "multi",
         "--teams", ",".join(teams),
         "--dry-run"],
        env={**os.environ, "CLAWSEAT_REAL_HOME": str(env_home)},
        capture_output=True, text=True,
    )
    assert proc.returncode == 0, f"install.sh failed: rc={proc.returncode} stderr={proc.stderr}"
    return proc.stdout


def _extract_toml(stdout: str) -> str:
    marker = "# Generated by render_project_toml_v3.py"
    idx = stdout.find(marker)
    assert idx >= 0, f"toml marker not found:\n{stdout}"
    end_idx = stdout.find("→ dry-run", idx)
    if end_idx < 0:
        end_idx = len(stdout)
    return stdout[idx:end_idx].rstrip()


# ---------- Slice 1: canonical install.sh multi-mode render ----------


def test_install_sh_multi_render_loads_via_runtime_loader(env_home, tmp_path):
    """install.sh --mode multi must produce a project.toml that the runtime
    profile loader accepts without KeyError. Audit fix 3: this test uses the
    real install.sh canonical entrypoint (not the internal install_multi.sh)."""
    project = "sts-dogfood"
    proposals = env_home / ".agents" / "tasks" / project / "_config-proposals"
    _make_approved_config(proposals, "core", project, [
        {"role": "planner", "tool": "claude", "provider": "anthropic",
         "auth_mode": "oauth_token", "model": "claude-opus-4-7",
         "rationale": "orchestration"},
        {"role": "builder", "tool": "claude", "provider": "anthropic",
         "auth_mode": "oauth_token", "model": "claude-sonnet-4-6",
         "rationale": "engine code"},
        {"role": "reviewer", "tool": "codex", "provider": "openai",
         "auth_mode": "api", "rationale": "code review"},
    ])
    _make_approved_config(proposals, "content", project, [
        {"role": "planner", "tool": "claude", "provider": "anthropic",
         "auth_mode": "oauth_token", "rationale": "orchestration"},
        {"role": "designer-creative", "tool": "gemini", "provider": "google",
         "auth_mode": "api", "rationale": "card design"},
    ])

    stdout = _run_canonical_install_multi(env_home, project, ["core", "content"])
    toml_text = _extract_toml(stdout)
    assert "team_structure = \"multi\"" in toml_text
    assert "core-builder" in toml_text
    assert "content-designer-creative" in toml_text
    assert "model = \"claude-opus-4-7\"" in toml_text

    # Round-trip through the runtime loader
    sys.path.insert(0, str(REPO_ROOT / "core" / "skills" / "gstack-harness" / "scripts"))
    from _common.profile import load_profile
    profile_path = env_home / "rendered.toml"
    profile_path.write_text(toml_text, encoding="utf-8")
    profile = load_profile(profile_path)
    assert profile.project_name == project


# ---------- Slice 2: brief CLI through canonical agent_admin entrypoint ----------


def _run_agent_admin(env_home: Path, *args: str) -> subprocess.CompletedProcess:
    """Invoke `python3 core/scripts/agent_admin.py ...` (canonical, not direct
    agent_admin_brief.py)."""
    return subprocess.run(
        ["python3", str(REPO_ROOT / "core" / "scripts" / "agent_admin.py"), *args],
        env={**os.environ, "CLAWSEAT_REAL_HOME": str(env_home)},
        capture_output=True, text=True,
    )


def test_canonical_brief_queue_list_claim_show(env_home, tmp_path):
    """Audit fix 3: exercise brief via canonical agent_admin entrypoint, not
    bypassing into agent_admin_brief.cmd_queue() directly. Doesn't claim to be
    end-to-end with live planner; just validates CLI plumbing."""
    project = "sts-dogfood"
    team = "core"

    r1 = _run_agent_admin(env_home, "brief", "queue",
                           "--project", project, "--team", team,
                           "--task-id", "STS-CORE-001",
                           "--objective", "Implement EffectExpression DSL v1.0 prototype",
                           "--seats-required", "builder", "reviewer")
    assert r1.returncode == 0, f"queue failed: {r1.stderr}"
    assert "queued task STS-CORE-001" in r1.stdout

    r2 = _run_agent_admin(env_home, "brief", "list",
                           "--project", project, "--team", team)
    assert r2.returncode == 0, r2.stderr
    assert "STS-CORE-001" in r2.stdout
    assert "task_created" in r2.stdout

    r3 = _run_agent_admin(env_home, "brief", "claim",
                           "--project", project, "--team", team,
                           "--task-id", "STS-CORE-001",
                           "--actor", "planner@claude")
    assert r3.returncode == 0, r3.stderr
    assert "claimed STS-CORE-001" in r3.stdout

    r4 = _run_agent_admin(env_home, "brief", "show",
                           "--project", project, "--team", team,
                           "--task-id", "STS-CORE-001")
    assert r4.returncode == 0, r4.stderr
    state = json.loads(r4.stdout)
    assert state["status"] == "task_claimed"
    assert state["actor"] == "planner@claude"


# ---------- Slice 3: contract publish + drift via library API ----------


def test_contract_publish_drift_cycle(env_home, tmp_path):
    """Publish a DSL contract, mutate runtime primitives, confirm drift detected.
    This is a library-level integration test, not E2E. The library is what
    patrol invokes per spec §4.6.3 — so it's the right surface to test."""
    from contract_drift_check import check_drift
    from contract_publish import publish_snapshot

    runtime = tmp_path / "EffectExpression__v1.0.0.yaml"
    runtime.write_text(
        "---\n"
        "contract_name: EffectExpression\n"
        "version: 1.0.0\n"
        "owner_team: core\n"
        "status: draft\n"
        "contract_type: dsl\n"
        "prototype_log:\n"
        "  - ts: '2026-05-14T00:00:00+00:00'\n"
        "    consumer_team: content\n"
        "    primitives_tested: [deal_damage, apply_poison, draw_cards]\n"
        "    verdict: sufficient\n"
        "sample_data:\n"
        "  - {primitive: deal_damage, value: 6, target: enemy}\n"
        "---\n"
        "# DSL grammar: effect := primitive(args*)\n",
        encoding="utf-8",
    )
    snap = publish_snapshot("EffectExpression", "1.0.0", "sts-dogfood",
                            runtime, consumers=["content"])

    r1 = check_drift("EffectExpression", "1.0.0", "sts-dogfood",
                     runtime_path=runtime, snapshot_path=snap)
    assert r1.in_sync, f"drifts after publish: {r1.drifts}"

    runtime.write_text(
        runtime.read_text().replace(
            "[deal_damage, apply_poison, draw_cards]",
            "[deal_damage, apply_poison, draw_cards, gain_block]",
        ),
        encoding="utf-8",
    )
    r2 = check_drift("EffectExpression", "1.0.0", "sts-dogfood",
                     runtime_path=runtime, snapshot_path=snap)
    assert not r2.in_sync


# ---------- Slice 4: fuzz harness on DSL primitive set ----------


def test_fuzz_harness_on_dsl_primitives(env_home, tmp_path):
    """Fuzz harness exercises EffectExpression DSL with random primitives —
    library-level test; brief.fuzz_required wiring is covered separately in
    test_phase3_round4.py / test_phase3_post_retest.py."""
    from fuzz_harness import run_fuzz

    spec = {
        "name": "effect_expr_v1.0_prototype",
        "generator": "expression",
        "primitives": ["deal_damage", "apply_poison", "draw_cards", "gain_block"],
        "max_depth": 3,
        "leaves": [1, 2, 3, "enemy", "self"],
    }

    def parse_effect(payload):
        if isinstance(payload, dict):
            assert "op" in payload
            assert payload["op"] in spec["primitives"]
            for a in payload.get("args") or []:
                parse_effect(a)

    result = run_fuzz(spec, target_fn=parse_effect, iterations=50, seed=42)
    assert result.ok, f"DSL parse fuzz failures: {result.failures[:3]}"
    assert result.cases_run == 50


# ---------- Honest scoping disclaimer test ----------


def test_module_does_not_claim_full_e2e():
    """Audit fix 3: this module deliberately stops short of true E2E because
    a live planner + tmux seats are required for that. Verify the module
    docstring acknowledges that limitation so future readers don't mistake
    these slices for end-to-end coverage."""
    docstring = __doc__ or ""
    assert "do NOT exercise a real planner seat end-to-end" in docstring, (
        "module docstring must explicitly disclaim full E2E scope"
    )
